const { autoGenerateDemandeAffectationForStockHouseKeeping, calculateStockRestant } = require('../utils/autoGenerateDemandeAffectation');
const DispatchHousekeeping = require('../models/DispatchHousekeeping');
const DispatchHousekeepingArticle = require('../models/DispatchHousekeepingArticle');
const DemandeAffectation = require('../models/DemandeAffectation');
const DemandeAffectationLigne = require('../models/DemandeAffectationLigne');
const Inventaire = require('../models/Inventaire');
const Chambre = require('../models/Chambre');
const { Op } = require('sequelize');

class StockMonitoringService {
  constructor() {
    this.isMonitoring = false;
    this.monitoringInterval = null;
    this.checkInterval = 60000; // 1 minute par défaut
    this.lastCheckTime = null;
    this.processedArticles = new Set(); // Pour éviter les doublons
  }

  /**
   * Démarre le monitoring en temps réel
   * @param {number} intervalMs - Intervalle de vérification en millisecondes (défaut: 60000 = 1 minute)
   */
  startMonitoring(intervalMs = 60000) {
    if (this.isMonitoring) {
      console.log('⚠️  Le monitoring est déjà actif');
      return;
    }

    this.checkInterval = intervalMs;
    this.isMonitoring = true;
    console.log(`🚀 Démarrage du monitoring des stocks (intervalle: ${intervalMs / 1000}s)`);

    // Vérification immédiate au démarrage
    this.checkStockLevels();

    // Vérification périodique
    this.monitoringInterval = setInterval(() => {
      this.checkStockLevels();
    }, this.checkInterval);
  }

  /**
   * Arrête le monitoring
   */
  stopMonitoring() {
    if (!this.isMonitoring) {
      return;
    }

    if (this.monitoringInterval) {
      clearInterval(this.monitoringInterval);
      this.monitoringInterval = null;
    }

    this.isMonitoring = false;
    console.log('🛑 Arrêt du monitoring des stocks');
  }

  /**
   * Vérifie les niveaux de stock et génère automatiquement les demandes si nécessaire
   */
  async checkStockLevels() {
    try {
      const startTime = Date.now();
      console.log('🔍 Vérification des niveaux de stock...');

      // Trouver l'espace "Stock House Keeping"
      const stockHousekeepingChambre = await Chambre.findOne({
        where: {
          [Op.or]: [
            { numero: 'Stock House Keeping' },
            { numero: 'Stock House keeping' },
            { numero: { [Op.like]: '%Stock House Keeping%' } }
          },
          type: 'Entrepôt'
        }
      });

      if (!stockHousekeepingChambre) {
        console.log('❌ Stock House Keeping espace non trouvé');
        return;
      }

      // Récupérer tous les articles qui sont dans Stock House Keeping
      const demandesApprouvees = await DemandeAffectation.findAll({
        where: {
          statut: 'approuvee'
        },
        include: [
          {
            model: DemandeAffectationLigne,
            as: 'lignes',
            where: {
              chambre_id: stockHousekeepingChambre.id
            },
            include: [
              {
                model: Inventaire,
                as: 'inventaire',
                attributes: ['id', 'nom', 'code_produit', 'quantite_min', 'stock_minimum', 'categorie']
              }
            ]
          }
        ]
      });

      // Extraire les articles uniques
      const articlesMap = new Map();
      demandesApprouvees.forEach(demande => {
        demande.lignes.forEach(ligne => {
          if (ligne.inventaire && !articlesMap.has(ligne.inventaire.id)) {
            articlesMap.set(ligne.inventaire.id, {
              id: ligne.inventaire.id,
              nom: ligne.inventaire.nom,
              code_produit: ligne.inventaire.code_produit,
              quantite_min: ligne.inventaire.quantite_min || ligne.inventaire.stock_minimum || 0,
              stock_minimum: ligne.inventaire.stock_minimum || ligne.inventaire.quantite_min || 0,
              categorie: ligne.inventaire.categorie
            });
          }
        });
      });

      const articles = Array.from(articlesMap.values());

      if (articles.length === 0) {
        console.log('ℹ️  Aucun article trouvé dans Stock House Keeping');
        this.lastCheckTime = Date.now();
        return;
      }

      // Vérifier chaque article
      const articlesEnRupture = [];
      for (const article of articles) {
        const stockRestant = await calculateStockRestant(article.id, stockHousekeepingChambre.id);
        const stockMinimum = parseFloat(article.quantite_min || article.stock_minimum || 0);

        // Générer une demande si la quantité restante est <= stock minimum
        if (stockRestant <= stockMinimum) {
          articlesEnRupture.push({
            ...article,
            stock_restant: stockRestant,
            stock_minimum: stockMinimum
          });
        }
      }

      if (articlesEnRupture.length === 0) {
        const duration = Date.now() - startTime;
        console.log(`✅ Vérification terminée - Aucun article en rupture (${duration}ms)`);
        this.lastCheckTime = Date.now();
        return;
      }

      console.log(`⚠️  ${articlesEnRupture.length} article(s) en rupture ou sous le seuil minimum détecté(s)`);

      // Vérifier s'il existe déjà une demande en attente pour ces articles
      const superviseurHousing = await require('../models/User').findOne({
        where: {
          role: 'Superviseur Housing',
          actif: true
        }
      });

      if (!superviseurHousing) {
        console.log('❌ Superviseur Housing non trouvé');
        this.lastCheckTime = Date.now();
        return;
      }

      const articleIds = articlesEnRupture.map(a => a.id);
      const existingDemandes = await DemandeAffectation.findAll({
        where: {
          demandeur_id: superviseurHousing.id,
          statut: 'en_attente'
        },
        include: [
          {
            model: DemandeAffectationLigne,
            as: 'lignes',
            where: {
              inventaire_id: { [Op.in]: articleIds },
              chambre_id: stockHousekeepingChambre.id
            }
          }
        ]
      });

      // Filtrer les articles qui ont déjà une demande en attente
      const articleIdsWithPendingDemande = new Set();
      existingDemandes.forEach(demande => {
        demande.lignes.forEach(ligne => {
          articleIdsWithPendingDemande.add(ligne.inventaire_id);
        });
      });

      const articlesToProcess = articlesEnRupture.filter(a => !articleIdsWithPendingDemande.has(a.id));

      if (articlesToProcess.length === 0) {
        const duration = Date.now() - startTime;
        console.log(`ℹ️  Toutes les ruptures ont déjà une demande en attente (${duration}ms)`);
        this.lastCheckTime = Date.now();
        return;
      }

      // Générer la demande automatique
      await this.generateDemandeForArticles(articlesToProcess, stockHousekeepingChambre, superviseurHousing);

      const duration = Date.now() - startTime;
      console.log(`✅ Vérification terminée - ${articlesToProcess.length} demande(s) générée(s) (${duration}ms)`);
      this.lastCheckTime = Date.now();

    } catch (error) {
      console.error('❌ Erreur lors de la vérification des stocks:', error);
      this.lastCheckTime = Date.now();
    }
  }

  /**
   * Génère une demande d'affectation pour les articles en rupture
   */
  async generateDemandeForArticles(articles, stockHousekeepingChambre, superviseurHousing) {
    try {
      console.log(`📝 Création d'une demande pour ${articles.length} article(s)...`);

      const demande = await DemandeAffectation.create({
        demandeur_id: superviseurHousing.id,
        statut: 'en_attente',
        commentaire: `Demande automatique générée suite à une rupture de stock dans Stock House Keeping (quantité restante <= stock minimum)`
      });

      const lignes = articles.map(article => {
        const stockMinimum = parseFloat(article.stock_minimum || article.quantite_min || 0);
        // Quantité demandée = double du stock minimum
        const quantiteDemandee = Math.max(1, Math.ceil(stockMinimum * 2));

        console.log(`   - ${article.nom}: quantité restante = ${article.stock_restant}, stock min = ${stockMinimum}, quantité demandée = ${quantiteDemandee}`);

        return {
          demande_affectation_id: demande.id,
          inventaire_id: article.id,
          chambre_id: stockHousekeepingChambre.id,
          quantite_demandee: quantiteDemandee,
          quantite_approvee: 0
        };
      });

      await DemandeAffectationLigne.bulkCreate(lignes);

      console.log(`✅ Demande d'affectation #${demande.id} créée automatiquement pour ${articles.length} article(s)`);

      return {
        success: true,
        demande_id: demande.id,
        articles_count: articles.length
      };
    } catch (error) {
      console.error('❌ Erreur lors de la génération de la demande:', error);
      throw error;
    }
  }

  /**
   * Vérifie un article spécifique après un changement
   */
  async checkArticleAfterChange(articleId, chambreId) {
    try {
      // Trouver l'espace "Stock House Keeping"
      const stockHousekeepingChambre = await Chambre.findOne({
        where: {
          [Op.or]: [
            { numero: 'Stock House Keeping' },
            { numero: 'Stock House keeping' },
            { numero: { [Op.like]: '%Stock House Keeping%' } }
          },
          type: 'Entrepôt'
        }
      });

      if (!stockHousekeepingChambre || stockHousekeepingChambre.id !== chambreId) {
        return; // Pas dans Stock House Keeping
      }

      const inventaire = await Inventaire.findByPk(articleId);
      if (!inventaire) {
        return;
      }

      const stockRestant = await calculateStockRestant(articleId, chambreId);
      const stockMinimum = parseFloat(inventaire.quantite_min || inventaire.stock_minimum || 0);

      // Si la quantité restante est <= stock minimum, générer une demande
      if (stockRestant <= stockMinimum) {
        console.log(`⚠️  Article ${inventaire.nom} (ID: ${articleId}) en rupture: ${stockRestant} <= ${stockMinimum}`);

        // Vérifier s'il existe déjà une demande en attente
        const superviseurHousing = await require('../models/User').findOne({
          where: {
            role: 'Superviseur Housing',
            actif: true
          }
        });

        if (!superviseurHousing) {
          console.log('❌ Superviseur Housing non trouvé');
          return;
        }

        const existingDemande = await DemandeAffectation.findOne({
          where: {
            demandeur_id: superviseurHousing.id,
            statut: 'en_attente'
          },
          include: [
            {
              model: DemandeAffectationLigne,
              as: 'lignes',
              where: {
                inventaire_id: articleId,
                chambre_id: chambreId
              }
            }
          ]
        });

        if (existingDemande) {
          console.log(`ℹ️  Une demande en attente existe déjà pour l'article ${inventaire.nom}`);
          return;
        }

        // Générer la demande
        await this.generateDemandeForArticles(
          [{
            id: inventaire.id,
            nom: inventaire.nom,
            code_produit: inventaire.code_produit,
            quantite_min: inventaire.quantite_min,
            stock_minimum: inventaire.stock_minimum || inventaire.quantite_min,
            categorie: inventaire.categorie,
            stock_restant: stockRestant
          }],
          stockHousekeepingChambre,
          superviseurHousing
        );
      }
    } catch (error) {
      console.error(`❌ Erreur lors de la vérification de l'article ${articleId}:`, error);
    }
  }

  /**
   * Obtient le statut du monitoring
   */
  getStatus() {
    return {
      isMonitoring: this.isMonitoring,
      checkInterval: this.checkInterval,
      lastCheckTime: this.lastCheckTime,
      nextCheckTime: this.lastCheckTime ? this.lastCheckTime + this.checkInterval : null
    };
  }
}

// Instance singleton
const stockMonitoringService = new StockMonitoringService();

module.exports = stockMonitoringService;

